# Course: Intro to Python & R for Data Analysis
## Lecture: Sentence Structures & Count Python-ula
Professor: Mary Kaltenberg

Fall 2020

contact: mkaltenberg@pace.edu

About me: www.mkaltenberg.com

## Objectives:


<table>
<tr><td style="text-align:left">
    <ul>
  <li>Review For Loops</li>
  <li>Nested Loops</li>
  <li>While and Break Statements</li>
  <li>Begin exploring the power of numpy</li>
    <ul>
      <li>what are elements, arrays and matrices</li>
       <li> basic statistic functions in numpy</li>
    </ul> 
</ul> 
</td><td>
<img src ="https://media.giphy.com/media/3o85xzkvl1siB2rHSo/giphy.gif" width = 250 >
</td></tr></table>
    

## For loops
Recall that for loops always begin with `for` followed by `in`. Generally it is:

`for item in iterable:
    Code to run`
    
The code to run can be combined with conditional statements and boolean expressions (and honestly, just about anything). We spent a lot of time talking about if, elif, and else conditions and a variety of boolean expressions - this will become very handy in for loops.

In [1]:
# Let's take the example of the nested conditional statement for loop
northeast = ['New York','New Jersey', 'Massachusettes','Vermont','New Hampshire','Maine',
             'Rhode Island','Connecticut','Pennsylvania']
for i in northeast:
    if i.startswith('N'):
        print('A state that start with N')
    elif i.startswith('M'):
        print('A state that start with M')
    else: 
        print('A state that starts with something else')
        
        

A state that start with N
A state that start with N
A state that start with M
A state that starts with something else
A state that start with N
A state that start with M
A state that starts with something else
A state that starts with something else
A state that starts with something else


In [2]:
# What if I want to add up the number of states in each of these categories?
# We can create variables that if the condition is met, it will add one and 
#do this iteratively until the end of the end of the list

nstates = 0
mstates =0 
otherstates= 0

northeast = ['New York','New Jersey', 'Massachusettes','Vermont','New Hampshire',
             'Maine','Rhode Island','Connecticut','Pennsylvania']
for i in northeast:
    if i.startswith('N'):
        nstates = nstates+1
    elif i.startswith('M'):
        mstates = mstates+1
    else: 
        otherstates = otherstates+1

In [3]:
print(nstates)
print(mstates)
print(otherstates)

3
2
4


#### Which variables are initalized in the above loop?
nstates, mstates, and other states

#### What happens if I don't initialize the above for loop?
it an error will pop up that nstates us not defined. We must defined the initial value for each variable.
if I already ran the loop and defined it, it will continue to count unless we reset it.

In [4]:
# How do I figure out the total number of items in the list?
total = len(northeast) # length is a function that can tell me how many element are in a list
fraction_nstates = nstates/total
fraction_mstates = mstates/total
fraction_otherstates = otherstates/total

#How can I simplify this code?

In [5]:
# we can create a for loop out of this and save the information into a list.

ne_statnames = [nstates, mstates, otherstates]  # create a list of items (our variables)
fraction=[] #initialize a list that is empty (contains no items), and name it fraction

for i in ne_statnames: 
    a = i/total # assign a variable a to be the fraction of the item divided by the total
    #(the item is the number if states in that category and total is number of elements in the list that we defined earlier)
    print(a)
    fraction.append(a) #for the list called fraction, append the value a in the list
fraction    

#this loop will calculate the fraction of states in the list and the append that number to a list called fraction 
# it will do this until the end of the list is reached

0.3333333333333333
0.2222222222222222
0.4444444444444444


[0.3333333333333333, 0.2222222222222222, 0.4444444444444444]

In [6]:
# You must initialize the list by creating a variable with an empty list
fraction=[]  # It's empty
type(fraction) #and you can see here this is a list

list

### Append

INCREDIBLY useful function. You will use this very often.

You create a variable that is an empty list, and as the loop proceeds it will add an item to the variable. Append can be used in a variety of settings including dataframes.

In [7]:
list1 = [3,9,15]
new_list = [] # create an empty list

for i in list1: # for each item in this list
    k = i*3 #multiple it by 3 and save it as the variable k
    new_list.append(k) # add the variable k to the list called new_list
new_list

[9, 27, 45]

## Nested Loops

A loop within a loop. What it will do is loop through the first set and then the second set in that order.

In [8]:
for i in range(1,5):
    print('outer loop item'+str(i))
    for j in range(6,9):
        print('inner loop item'+str(i))

outer loop item1
inner loop item1
inner loop item1
inner loop item1
outer loop item2
inner loop item2
inner loop item2
inner loop item2
outer loop item3
inner loop item3
inner loop item3
inner loop item3
outer loop item4
inner loop item4
inner loop item4
inner loop item4


In [9]:
# Let's take the example of the nested conditional statement for loop
northeast = ['New York','New Jersey', 'Massachusettes','Vermont','New Hampshire',
             'Maine','Rhode Island','Connecticut','Pennsylvania']
newengland = ['Massachusettes','Vermont','New Hampshire','Maine','Rhode Island']
tot_states_ne = 0

for i in northeast:  # In this loop look at the first item and;
    print(i) # print the value i
    if i in newengland: # then evaluate if the item i is in the list new england
        print(i, 'is in new england') # if that's true, print this statement
        tot_states_ne = tot_states_ne+1 # and add 1 to the variable tot_state_ne; 
#         move onto the next item in the list new england until there are no more items, 
# then go to the next item in the list northest
tot_states_ne

New York
New Jersey
Massachusettes
Massachusettes is in new england
Vermont
Vermont is in new england
New Hampshire
New Hampshire is in new england
Maine
Maine is in new england
Rhode Island
Rhode Island is in new england
Connecticut
Pennsylvania


5

In [10]:
# Adding 1 that initalizes at 0 is very useful to help you count 
# The total cout at the end of this for loop will show you how many iterations it took to complete the for loop
counter = 0
for i in northeast:
    
    if i in newengland:
        print(i, 'is in new england')
    
    counter = counter+1
counter

Massachusettes is in new england
Vermont is in new england
New Hampshire is in new england
Maine is in new england
Rhode Island is in new england


9

Another way to have a counter is to use an addition assignment `+=`

`+=` can be very useful to continually add one to a variable. This is often used in counters to help you keep track of the number of iterations that you 

This is equivalent to i = i+1

In [11]:
counter = 0
for i in northeast:
    
    if i in newengland:
        print(i, 'is in new england')
    
    counter +=1
counter

Massachusettes is in new england
Vermont is in new england
New Hampshire is in new england
Maine is in new england
Rhode Island is in new england


9

The above nested loop will first look at the first item (New York) in the first list (northeast) and then look at all of the items in the second list (newengland) that meets the conditional statement. Then it will go to the second item (New Jersey) in the first list (northeast) and then go through all of the items in the second list (newengland).

Be careful with nested loops in the logic. Loops will go in order of the loop identified. It will always go to list one and then all the iteams in list two iteratively.

### In line Nest Loops
A very cool feature in python is that you can simplify nested loops and code them in one line and append them. This is very useful for appending data in one line of code. 

Essentially, after calculating each item, it creates a list out of the results from each iteration and compiling them into one variable (when assigned).

Also called list comprehension.

`[somecode for i in list1 for j in list2]`

You can't do this in a nested block (many multiple conditions)

In [12]:
#To be exactly as stated as before
nelist = [i+str(' is in new england') for i in northeast if i in newengland]

when you add components to the item i you add the string and denote that information is a string with str() notice the formatting of item i plus the string

this is important to make a habit of so that you don't mix types up, if you do, you will get an error

In this case the item i is already a string, so it won't give you an error, but it is good practice to always define the type when you add strings.

You don't have to use them, but they make code simplified  - we ran a nested loop in one line without having to use the function append


In [13]:
# If I assign i to be a number and add it to a string, you will get an error
i = 7
# i + 'bob'

In [14]:
# When I add elements together, I have to make sure it is the same type
i = str(7)
i+' bob'

'7 bob'

In [15]:
i = 7
7+9

16

In [16]:
# Let's go through another example of nested loops
list1 = [3,9,12]
x = 0
answers = []

for i in range(5,10): # for each item in the range of numbers 5 through 9
    if (i % 2) == 0: # check to see if i is even (that the remainder of i divided by 2 is equal to 0)
        #, if it is true then do code below; if false, move to next conditional
        x = i*3 #multiple i by 3 and save it with the variable x
    else: #otherwise
        for j in list1: # for items that are in list1 and add 5 then,
            x = j+5
    answers.append(x) # append all of these answers from this loop in one list
    
#what happens if answers.append(x) is tabbed inward?
answers

[17, 18, 17, 24, 17]

### Let's take this step by step
1. for each item in the range of numbers 5 through 9
2. Check if that item is even (if the modular of i divided by 2 is equal to 0)
    - If it is true, multiple that number by 3
    - if it is false, move to the next condition
##### Modular
`%` is the remainder of an equation in mathematics. It can be very useful for identifying even numbers, as above, or if you want to divide blocks of data evenly and spread the remainder evenly across other groups. 

3. else condition; (otherwise)
   - for each item j in the list called list1
    - check to see if the item i is equal to j
        - if it is true, add 5
        - if it is false, move to the next item j
        - if all items j run, move to next code    
4. whatever is in x, add x to the list called answers

Now let's apply the numbers
For the item 5 in the range 5-9
2. is the modular of 5 divided by 2 is equal to 0?
False; go to next condition
3. else: (otherwise)
    - if 5 == 3
    - False
    - if 5 == 9
    - False
    - if 5 == 12
    - False
4. append the value of x (0) to the list answers

Note: we initialized x to be equal to 0, because there is no additional changes to x after going through this loop, it will append the value of x which is currently 0.
Go to next item in range

For the item 6 in the range 5-9

2. is the modular of 6 divided by 2 is equal to 0?

True
    - multiply 6*3 and save it in the value x
     (x = 18)
    - go to next code
<!-- 3. else: (otherwise)
    - if 6 == 3
    - False
    - if 6 == 9
    - False
    - if 6 == 12
    - False -->
4. append the value of x (18) to the list answers

For the item 7 in the range 5-9
2. is the modular of 7 divided by 2 is equal to 0?
False; go to next conditional
<!-- 3. else: (otherwise)
    - if 7 == 3
    - False
    - if 7 == 9
    - False
    - if 7 == 12
    - False -->
False; go to next code
4. append the value of x (18) to the list answers
(that is because the value of x has not changed) in this loop

For the item 8 in the range 5-9
2. is the modular of 8 divided by 2 is equal to 0?
True; 
    - multiply 8*3 and save it in the value x
     (x = 24)
    - go to next conditional/line
<!-- 3. else: (otherwise)
    - if 8 == 3
    - False
    - if 8 == 9
    - False
    - if 8 == 12
    - False
    
False; go to next code -->
4. append the value of x (24) to the list answers

For the item 9 in the range 5-9
2. is the modular of 9 divided by 2 is equal to 0?
False; go to next conditional
3. else: (otherwise)
    - if 9 == 3
    - False
    - if 9 == 9
    - True!
    
    add 5 to 9 an define it to be x (14)

4. append the value of x (14) to the list answers


In [17]:
#Another example
x_list = [10,57,89,76,350,126]
for i in range(25, 350, 25):
    x = i +20
    for j in x_list:
        if j>100:
            x_list = [x-1,j]
        else: 
            x_list2 = [x,j]

1. For every item i in the range of 25 to 350 going by 25 (25, 50, 75, etc until 100) add 20 and call that variable x
2. For each item j in x_list check to see if the item j in x_list is above 100, if that's true, subtract 1 from x, create a list and call it x_list, otherwise create a list with x and j and name it x_list2
3. Go back to the next item in the range 25 to 350 going by 25 and do it again until there are no more items.

## While


while loops are useful when the number of iterations needed depends on the outcome of the loop contents. 

while loops are commonly used when a loop should only stop if a certain condition is met, such as the number of iterations or if changes are incrementally smaller. The generic structure of a while loop is:
 
 `while logical:
     run code
     update logical`
 
2 things are crucial when using a while loop: 
- the logical expression must be true when the loop begins (or the loop will be ignored) 
- the inputs to the logical expression must be updated inside the loop. If they are not, the loop will continue indefinitely



## break
Break are conditions in which your loop will stop when you meet them. It's useful to have breaks if it's something that could potentially go on infinitely. 

It should almost always be used with the while condition so you can put a break in the infinite cycle, but if a while loop is correctly formatted, you don't have to use it (though, I think it's good to use breaks anyways)

In [18]:
i = [1,2,3,4,5]
i[0:5]

[1, 2, 3, 4, 5]

In [19]:
#while loops will continue until the logical statement that you input is False. 
# In this case, the logical statement is i less than 20.
# The while loop will stop when it hits 20 because 20 is not less than 20 (Thus the last number printed is 19)

i = 1
while i < 20:
    print(i)
    i += 1 

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [20]:
#In this case, if i is great than 0, the logical statement will always be True 
# The loop will be indefinite
# This is why we must use the break function to tell the loop when to stop.  
# Here, the if condition is used and when that if condition is True it will run the following line
# Which is to stop the loop (break)

i = 1
while i > 0:
    print(i)
    if i == 5:
        break
    i += 1 

1
2
3
4
5


In [21]:
# Interest rates on loans example

# suppose you have a loan that starts at 45,832 and the interest rate is 2.75
# here is an example of calculating loans and interest rates with a while loop
i = 45832
y = 0
while i > 0:
    i = i*1.0275
    y += 1
    if y > 15:
        break
print('loan after 15 years of interest', round(i,2))

#note this assumes that you are not paying it off every month. This is the cost of loan without payments
# For an exercise, write a while loop that includes monthly payments of $300

#If I didn't use the break function, this lop would be indefinite because i is always greater than 0 in this loop.

loan after 15 years of interest 70742.12


# Numpy

In [22]:
import numpy as np
#I'm calling the book numpy from my library to use in this notebook

Numpy is a package that works with multi-dimesnional arrays to apply mathematical functions and statistics. It does more than this, but that's what we're interested in for this class.

Arrays are similar to lists - they contain elements. However, arrays are much more efficient. This is VERY important when dealing with large data. 

Why Numpy instead of lists?
- It's faster
- Stores less memory
- Has integrated statistics and math programs

Arrays can have n dimensions. In lists, mathematical operators operate element by element, but in arrays and matrices can use the rules of linear algebra (but also element by element). 

We won't get into it, but linear algebra is SUPER helpful in econometrics and computer science. A great place to start is the essence of [linear algebra youtube series](https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab) by 3blue1brown

Yes, it's math, but it's not as scary as it seems!

It's also a gateway to learning how to work with data in pandas (That's where the real fun begins)!

In [23]:
# 0 dimensional arrays
np.array(1)

array(1)

In [24]:
# One dimensional arrays
d_1 = np.array([1,4,3,5,8,19])

In [25]:
# 2 dimensional arrays
d_2 = np.array([[1,4,5],[3,5,6],[3,5,6],[3,5,6]])

In [26]:
# 3 dimensional arrays
d_3 = np.array([[[1, 2], [3, 6]], [[1, 6], [9, 8]]])
# <-  the square brackets are very important to determine the dimension

#### Remember that the format of shape is: (N rows, N columns)

In [27]:
print(d_2.ndim) # The number of dimensions
print(len(d_2)) # number of elements in each dimension
print(d_2.shape) # the shape of the array (N rows, N columns)

2
4
(4, 3)


In [28]:
d_2 = np.array([[-2,5,6],[5,2,7]])
print(d_2.shape)

(2, 3)


Shape is the matrix size. Recall long ago in a world of math where matrixes look like:
<img src ="matrix.png">

In [29]:
# You can turn arrays into matrices as long as it has 2 dimensions
matrix = np.matrix(d_2)
matrix

matrix([[-2,  5,  6],
        [ 5,  2,  7]])

### Example

Let's take an example of things that numpy can do for you.

In [30]:
#let's go back to the interest loan code and create a list of numbers
i = 45832
y = 0
loan = []
while i > 0:
    i = i*1.0275
    y += 1
    loan.append(round(i,2))
    if y > 15:
        break

In [31]:
# we can assign a new variable that creates an array from a list
loan_array = np.array(loan)

Imagine I want to know the total cost of the loan that includes fees, and I have a list of fees for years 1-15, but they are all different rates. You can use numpy to multiply the two arrays together.

In [32]:
fees = [1.002,1.002,1.003,1.003,1.004,1.005,1.006,1.005,1,1.004,1.001,1.00,1.002,1.003,1.003,1.002]
fees = np.array(fees)

In [33]:
#let's check that both of the arrays are the same dimension and length
print(len(fees),len(loan_array))
print(fees.ndim,loan_array.ndim)

16 16
1 1


In [34]:
fees*loan_array

array([47186.56476, 48484.19484, 49867.22421, 51238.57596, 52700.13068,
       54203.31825, 55749.32092, 57225.49395, 58506.66   , 60356.05236,
       61830.53877, 63467.41   , 65343.18552, 67207.12833, 69055.32634,
       70883.60424])

In [35]:
#see that I have to call np to use the round function when dealing with arrays
total_loan_cost = np.round(fees*loan_array,2)
total_loan_cost

array([47186.56, 48484.19, 49867.22, 51238.58, 52700.13, 54203.32,
       55749.32, 57225.49, 58506.66, 60356.05, 61830.54, 63467.41,
       65343.19, 67207.13, 69055.33, 70883.6 ])

In [36]:
total_loan_cost

array([47186.56, 48484.19, 49867.22, 51238.58, 52700.13, 54203.32,
       55749.32, 57225.49, 58506.66, 60356.05, 61830.54, 63467.41,
       65343.19, 67207.13, 69055.33, 70883.6 ])

Numpy calculates basic operations element by element, but it will do linear algebra and calculate operations with linear algebra when told. This is partly what makes it super fast.

<img src="https://media.giphy.com/media/2tVKdyhY1v7oY/giphy.gif">


Anything you can do with linear algebra, you can do with numpy:
   - cross product
   - transpose
   - dot products
   - inverse
   - eigenvalues
   - identity
   - etc. 
   
  I won't go over this, but it's handy to know. Econometrics uses linear algebra intensively, so for those taking that course next semester - refresh your linear algebra for next semester to make your life easier.
  

In [37]:
#Let's say you have multiple loans with varying fee schedules
#let's go back to the interest loan code and create a list of numbers

i = 35800
y = 0
loan_2 = []

while i > 0:
    i = i*1.0375
    y += 1
    loan_2.append(round(i,2))
    if y > 15:
        break

In [38]:
#We can create a matrix out of that information
all_loans = np.matrix([loan,loan_2])

In [39]:
# I can change the columns and rows with reshape to the specific shape I want
np.reshape(all_loans,(16,2))

matrix([[47092.38, 48387.42],
        [49718.07, 51085.32],
        [52490.17, 53933.65],
        [55416.82, 56940.79],
        [58506.66, 60115.59],
        [61768.77, 63467.41],
        [65212.76, 67006.11],
        [68848.78, 70742.12],
        [37142.5 , 38535.34],
        [39980.42, 41479.68],
        [43035.17, 44648.99],
        [46323.33, 48060.45],
        [49862.72, 51732.57],
        [53672.54, 55685.27],
        [57773.46, 59939.97],
        [62187.72, 64519.76]])

In [40]:
# transpose is also useful
all_loans = np.transpose(all_loans)

Matrices is another way to store data

They are very similar frameworks that you see when opening a csv file of data

Matrices in numpy can only deal with numbers, but as you can see the framework is very similar

<img src='dataframe.jpg'>

In [41]:
all_loans_2 = all_loans

### Slicing

You can also access any element in an array or matrix like you would by slicing (remember that from earlier lectures?)

Slicing works in the same way where negative numbers go from the end.

In [42]:
#1-d array
total_loan_cost

array([47186.56, 48484.19, 49867.22, 51238.58, 52700.13, 54203.32,
       55749.32, 57225.49, 58506.66, 60356.05, 61830.54, 63467.41,
       65343.19, 67207.13, 69055.33, 70883.6 ])

In [43]:
print(total_loan_cost[5])
total_loan_cost[14:]

54203.32


array([69055.33, 70883.6 ])

In [44]:
# Matrix (recall that we created a matrix earlier)
all_loans

matrix([[47092.38, 37142.5 ],
        [48387.42, 38535.34],
        [49718.07, 39980.42],
        [51085.32, 41479.68],
        [52490.17, 43035.17],
        [53933.65, 44648.99],
        [55416.82, 46323.33],
        [56940.79, 48060.45],
        [58506.66, 49862.72],
        [60115.59, 51732.57],
        [61768.77, 53672.54],
        [63467.41, 55685.27],
        [65212.76, 57773.46],
        [67006.11, 59939.97],
        [68848.78, 62187.72],
        [70742.12, 64519.76]])

In [45]:
# so, if we want the first row we can call it:
all_loans[0]

matrix([[47092.38, 37142.5 ]])

Remember from Algebra the matrix locations:
    
<img src = "matrix_location.png" width = 400>

This works in the same way for index slicing in python (but with 0 indexing)

In [46]:
# If we want the first column
all_loans[:,0]
# This says, show me all of the rows of the second column.

matrix([[47092.38],
        [48387.42],
        [49718.07],
        [51085.32],
        [52490.17],
        [53933.65],
        [55416.82],
        [56940.79],
        [58506.66],
        [60115.59],
        [61768.77],
        [63467.41],
        [65212.76],
        [67006.11],
        [68848.78],
        [70742.12]])

The colon `:` is important to understand. The colon asks for information *until* a certain point

In [47]:
# For example:
# If we want the first column with rows 1 through 5
all_loans[0:5,0]
# Here, it will print rows 1 through 5 or, in other words, indexed items at 0 UNTIL 5 (indexed item 1 through 4)

matrix([[47092.38],
        [48387.42],
        [49718.07],
        [51085.32],
        [52490.17]])

Go back to the above diagram and connect the locations in our all_loans matrix with the diagram

<img src= "slicing_example.png">

In [48]:
#How do we get the second column with rows 1 through 3?

Understanding this will help you access particular data rows or columns or sections within any numpy or pandas (will get to it soon)

Another useful visual from P4DS

<img src = "matrix_slicing_diagram.png" >

## Filtering

You can use boolean functions to filter data or even replace data in arrays/matrices. You will be using this a lot to filter data when we get to pandas.

Remember those boolean functions we talked about last lecture? You'll use them a lot for filtering. 

To filter the syntax is always the assigned variable with hard brackets and then the boolean function related to the particular assigned variable:

`variable[variable >= N]`

If you are using more than one boolean function, you need to separate the boolean requests with tuples:

`variable[(variable >= N) & (variable < N)]`

In [49]:
all_loans[(all_loans > 65000)]

matrix([[65212.76, 67006.11, 68848.78, 70742.12]])

In [50]:
all_loans[(all_loans < 40000)]

matrix([[37142.5 , 38535.34, 39980.42]])

In [51]:
all_loans[(all_loans >65000) & (all_loans <67000)]

matrix([[65212.76]])

In [52]:
all_loans[(all_loans==65212.76)]

matrix([[65212.76]])


np.nan is to mark something as "missing" in python

When you see `NaN` that means a value is missing

You can search if something is missing by looking for np.nan

In addition, sometimes you will get `Inf` which means the value is infinite - this can happen often

You'll want to learn how to search for these values often - usually to clean data 

In [53]:
# We can use these additional conditionals to replace values in the matrix
# that meet the true condition
all_loans[(all_loans >65000)& (all_loans <67000)] = np.nan
all_loans[(all_loans <38000)] = np.inf

<ipython-input-53-04f5222d9835>:4: RuntimeWarning: invalid value encountered in less
  all_loans[(all_loans <38000)] = np.inf


In [54]:
all_loans

matrix([[47092.38,      inf],
        [48387.42, 38535.34],
        [49718.07, 39980.42],
        [51085.32, 41479.68],
        [52490.17, 43035.17],
        [53933.65, 44648.99],
        [55416.82, 46323.33],
        [56940.79, 48060.45],
        [58506.66, 49862.72],
        [60115.59, 51732.57],
        [61768.77, 53672.54],
        [63467.41, 55685.27],
        [     nan, 57773.46],
        [67006.11, 59939.97],
        [68848.78, 62187.72],
        [70742.12, 64519.76]])

## Remember np.isnan()  and np.isinf() functions - you will use this OFTEN


<img src ="https://media.giphy.com/media/xT5LMwEYkU01OIa46c/giphy.gif" width = 250>

In [55]:
#let's search for these values
np.isnan(all_loans)

matrix([[False, False],
        [False, False],
        [False, False],
        [False, False],
        [False, False],
        [False, False],
        [False, False],
        [False, False],
        [False, False],
        [False, False],
        [False, False],
        [False, False],
        [ True, False],
        [False, False],
        [False, False],
        [False, False]])

In [56]:
#we can also filter for only true values from the matrix 
# that are nan by creating a list of all values that are True
all_loans[np.isnan(all_loans)]

matrix([[nan]])

In [57]:
# Here you can search for a boolean in the matrix to exclude anythign that is a nan
# -> You MUST do the tilda to look exclude nan
# It's kind of like an exclusion boolean. Show me everything but what I asked for.
all_loans[~np.isnan(all_loans)]

matrix([[47092.38,      inf, 48387.42, 38535.34, 49718.07, 39980.42,
         51085.32, 41479.68, 52490.17, 43035.17, 53933.65, 44648.99,
         55416.82, 46323.33, 56940.79, 48060.45, 58506.66, 49862.72,
         60115.59, 51732.57, 61768.77, 53672.54, 63467.41, 55685.27,
         57773.46, 67006.11, 59939.97, 68848.78, 62187.72, 70742.12,
         64519.76]])

In [58]:
all_loans[~np.isinf(all_loans)]

matrix([[47092.38, 48387.42, 38535.34, 49718.07, 39980.42, 51085.32,
         41479.68, 52490.17, 43035.17, 53933.65, 44648.99, 55416.82,
         46323.33, 56940.79, 48060.45, 58506.66, 49862.72, 60115.59,
         51732.57, 61768.77, 53672.54, 63467.41, 55685.27,      nan,
         57773.46, 67006.11, 59939.97, 68848.78, 62187.72, 70742.12,
         64519.76]])

### Python Byte Moment

Another great thing about python coding is that you can tack on functions in one line of code.

The order of a function is always done by taking the first from the left onwards.

In [59]:
# here is an example that I create an array and then I ask it to tell me the dimension of the array
#python will output the last function you ask it to, but it will also calculate everythign prior
np.array([[1,4],[3,5]]).ndim

2

In [60]:
#otherwise, you would have to assign it and then tell it what to do next in order
x = np.array([[1,4],[3,5]])
x.ndim

2

In [61]:
x = np.array([[1,4],[3,5]]).ndim
x

2

By tacking on functions, it saves memory, so that you don't have to save every step that you do in your code and it will output the last function you really need to save. 

It is cumulative - this will be VERY handy in pandas (and generally)

In [62]:
x_list =[34,62,35,647,45,29,68,3,55]
x_list = np.array(x_list)

In [63]:
# The above is the same as the code below
x_list = np.array([34,62,35,647,45,29,68,3,55])

## Useful Functions in Numpy

Where you will combine numpy and pandas is calculating statistics or math. 

It is very fast, efficient, and pandas doesn't have all of the math funcitons that numpy has. I'll go over the main functions you will likely use - but, you may have to use a funciton I never went over and learn how to use it on your own (including in assignments). 

Coding is learning how to apply new functions that you never new about before to a particular puzzle or step you want to do. It's a combination of logical thinking and creativity. 

I'll include snapshots from the P4DS book for your reference that are helpful to refer to - the book can explain the difference in the operations computationally, but for our purposes, it's not really necessary to understand the backend.

### Some Useful Functions

For an array or a matrix - it will perform the operation element by element

In [64]:
#square root
np.sqrt(loan)

array([217.00778788, 219.97140723, 222.97549193, 226.02061853,
       229.10733292, 232.23619442, 235.40777387, 238.62269381,
       241.88149991, 245.18480785, 248.53323721, 251.92739033,
       255.36789148, 258.85538434, 262.3905105 , 265.97390849])

In [65]:
np.square(loan)

array([2.21769225e+09, 2.34134241e+09, 2.47188648e+09, 2.60970992e+09,
       2.75521795e+09, 2.90883860e+09, 3.07102394e+09, 3.24225357e+09,
       3.42302926e+09, 3.61388416e+09, 3.81538095e+09, 4.02811213e+09,
       4.25270407e+09, 4.48981878e+09, 4.74015451e+09, 5.00444754e+09])

In [66]:
#matrix
np.square(all_loans_2)

matrix([[2.21769225e+09,            inf],
        [2.34134241e+09, 1.48497243e+09],
        [2.47188648e+09, 1.59843398e+09],
        [2.60970992e+09, 1.72056385e+09],
        [2.75521795e+09, 1.85202586e+09],
        [2.90883860e+09, 1.99353231e+09],
        [3.07102394e+09, 2.14585090e+09],
        [3.24225357e+09, 2.30980685e+09],
        [3.42302926e+09, 2.48629085e+09],
        [3.61388416e+09, 2.67625880e+09],
        [3.81538095e+09, 2.88074155e+09],
        [4.02811213e+09, 3.10084929e+09],
        [           nan, 3.33777268e+09],
        [4.48981878e+09, 3.59280000e+09],
        [4.74015451e+09, 3.86731252e+09],
        [5.00444754e+09, 4.16279943e+09]])

In [67]:
#exponential (also for numbers)
np.exp(2.713)

15.07443104084234

In [68]:
# or an array
np.exp(np.sqrt(loan))

array([1.75907682e+094, 3.40697022e+095, 6.87109168e+096, 1.44380128e+098,
       3.16264505e+099, 7.22599632e+100, 1.72304726e+102, 4.29061135e+103,
       1.11635080e+105, 3.03675039e+106, 8.64198467e+107, 2.57439665e+109,
       8.03278468e+110, 2.62702998e+112, 9.01053989e+113, 3.24340207e+115])

In [69]:
#What's the base of this?
np.log(loan)

array([10.75986648, 10.78699514, 10.81412373, 10.84125246, 10.86838119,
       10.89550987, 10.92263844, 10.94976723, 10.97689587, 11.00402449,
       11.03115318, 11.05828182, 11.08541043, 11.11253909, 11.13966778,
       11.16679643])

In [70]:
np.log10(loan)

array([4.67295064, 4.68473247, 4.69651426, 4.70829612, 4.72007798,
       4.73185981, 4.7436416 , 4.75542349, 4.76720531, 4.77898711,
       4.79076895, 4.80255078, 4.81433258, 4.82611441, 4.83789625,
       4.84967807])

In [71]:
# absolute values
np.abs(loan)

array([47092.38, 48387.42, 49718.07, 51085.32, 52490.17, 53933.65,
       55416.82, 56940.79, 58506.66, 60115.59, 61768.77, 63467.41,
       65212.76, 67006.11, 68848.78, 70742.12])

In [72]:
#round to the nearest integer
# (particularly useful when cleaning data and need to convert to integer)
np.rint(loan)

array([47092., 48387., 49718., 51085., 52490., 53934., 55417., 56941.,
       58507., 60116., 61769., 63467., 65213., 67006., 68849., 70742.])

## Basic Statistics

<img src ="basic_statistics.png">


## Set Operations

<img src ="setoperations.png">

## Calculations within a Matrix or Array

In [91]:
all_loans[0:1,1]= 57773.46
all_loans[12:13,0] = 37142.5

In [117]:
all_loans

matrix([[47092.38, 57773.46],
        [48387.42, 38535.34],
        [49718.07, 39980.42],
        [51085.32, 41479.68],
        [52490.17, 43035.17],
        [53933.65, 44648.99],
        [55416.82, 46323.33],
        [56940.79, 48060.45],
        [58506.66, 49862.72],
        [60115.59, 51732.57],
        [61768.77, 53672.54],
        [63467.41, 55685.27],
        [37142.5 , 57773.46],
        [67006.11, 59939.97],
        [68848.78, 62187.72],
        [70742.12, 64519.76]])

In [118]:
#minimum value of the entire matrix
all_loans.min()

37142.5

In [116]:
#minimum value for EACH row
all_loans.min(axis=1)

matrix([[47092.38],
        [38535.34],
        [39980.42],
        [41479.68],
        [43035.17],
        [44648.99],
        [46323.33],
        [48060.45],
        [49862.72],
        [51732.57],
        [53672.54],
        [55685.27],
        [37142.5 ],
        [59939.97],
        [62187.72],
        [64519.76]])

For nearly all function in numpy, you can tell it to calculate specific aspects of your matrix or array by indicating the axis that it should focus on. 

`all_loans.min(axis=1)` is saying to find the minimum value for EVERY Row (axis 1)


<img src = array_method_axis_1.svg>

In [115]:
#minimum value for EACH column
all_loans.min(axis=0)

matrix([[37142.5 , 38535.34]])

For nearly all function in numpy, you can tell it to calculate specific aspects of your matrix or array by indicating the axis that it should focus on. 

`all_loans.min(axis=0)` is saying to find the minimum value for EVERY columns (axis 0)


<img src = array_method_axis_0.svg>

## Random function

In [74]:
np.random.rand(8,6)

array([[0.38046557, 0.66629863, 0.06587408, 0.577106  , 0.0369011 ,
        0.19093294],
       [0.1697295 , 0.53104057, 0.32599587, 0.27412462, 0.35315085,
        0.66655524],
       [0.21227391, 0.45493262, 0.56295679, 0.40258023, 0.93335249,
        0.80039512],
       [0.38824748, 0.42156068, 0.57107801, 0.95766292, 0.58570058,
        0.3991592 ],
       [0.87657333, 0.33427314, 0.39666713, 0.64493429, 0.14187043,
        0.12098023],
       [0.79461242, 0.75692468, 0.0752231 , 0.63550499, 0.69767969,
        0.55533046],
       [0.74439142, 0.48524941, 0.15660819, 0.36118712, 0.83213881,
        0.96074537],
       [0.06043212, 0.30321413, 0.47769864, 0.25820263, 0.89212746,
        0.09488877]])